### ISSUE TITLE
[Applications] Suggestions for actions

### ISSUE THREAD

**Issue by abenz1267** [Kirottu/anyrun#10]
Hi,

i have two small suggestions:

1. currently actions get shown as `app: action`. I'd suggest being able to show the action as the title and the app as the description, so you have:
```
New Private Window
Firefox Developer Edition
```

Otherwise those actions get get very long. Imagine someone using the plugin info box, has icons enabled AND actions. That's either one long ass box or you get ugly line-breaks.

2. the sorting could need improvement, f.e. when i type in "thunderbird" i get this as the result:
![image](https://user-images.githubusercontent.com/7055955/230861368-ffffe970-bf73-42eb-9335-d896038c93da.png)

I'd expect "Thunderbird" to be the first result.

What do you think?

Regards

**Comment by Kirottu** [comment]
Oh, I didn't even think of that. Seems like a really good idea.

As for the sorting, I was a bit confused by it as well but aren't quite sure why the fuzzy match lib does it like that.

**Comment by Kirottu** [comment]
Hm, it seems like moving the main desktop entry name to the description also helped with the sorting.
![image](https://user-images.githubusercontent.com/56396750/231101812-22f85ab4-a9a2-4b07-99e9-67679c46b5e3.png)

**Comment by abenz1267** [comment]
Indeed!

Slightly off-topic: i think you'd provide "native" plugins from somekinda shared lib folder or something, so that updating via AUR or whatever also updates the plugins. Right now you need to update plugins manually.

Regards

**Comment by Bryntet** [comment]
> Indeed!
> 
> Slightly off-topic: i think you'd provide "native" plugins from somekinda shared lib folder or something, so that updating via AUR or whatever also updates the plugins. Right now you need to update plugins manually.
> 
> Regards

Right now the AUR actually does update the native plugins. It copies them into the right spot after you've updated the package. :)

**Comment by Kirottu** [comment]
It matches both the name of the entry and the executable, so one could type in something like `pavucontrol` and still get `PulseAudio Volume Control`. I am quite confused as to how the fuzzy matching weights the exec line with more stuff over the more minimal one though. Probably would need adjusting the weights.

**Comment by Kirottu** [comment]
Alright I made a change to the sorting so that the scores for matching with the name and the exec are summed for the final comparison. Do test it and if you have any ideas for the sorting do let me know.

**Comment by abenz1267** [comment]
Looks fine to me!
