### ISSUE TITLE
Stdin plugin deprecated??

### ISSUE THREAD

**Issue by cybergaz** [Kirottu/anyrun#112]
there's no way to get this plugin working.
what about that **-o** option mentioned in the readme??
is it deprecated or what??

**Comment by zhuyk6** [comment]
You can use `echo -e "ha\nhaha" | anyrun --plugins libstdin.so` instead.

**Comment by cybergaz** [comment]
@zhuyk6 is there any way to print all of the content first , instead of search then show??
