### ISSUE TITLE
Not loading applications when $XDG_DATA_HOME/applications doesn't exist

### ISSUE THREAD

**Issue by n3oney** [Kirottu/anyrun#18]
Currently, when the `$XDG_DATA_HOME/applications` folder doesn't exist, the applications plugin will error out with this message: `Failed to load desktop entries: No such file or directory (os error 2)` and won't load any apps.
Not everyone has to have that directory, so it'd be nice to just ignore it if it doesn't exist.

Naturally, there's a simple workaround for the time. Just create the directory.

**Comment by Kirottu** [comment]
The code skips over any directories it can't read when looking for the desktop entries, so it shouldn't matter if a single directory is missing. But what you describe seems like there are no valid directories in `$XDG_DATA_HOME`.

**Comment by n3oney** [comment]
XDG_DATA_DIRS is the variable that contains the list of directories that the program should scan, and yes, it does skip over nonexistent directories in here.
However, XDG_DATA_HOME is added [explicitly](https://github.com/Kirottu/anyrun/blob/master/plugins/applications/src/scrubber.rs#L165) after the XDG_DATA_DIRS scanning.

**Comment by Kirottu** [comment]
Oh right, I got confused over env var names. And yes I see the issue now.

**Comment by Kirottu** [comment]
Should be fixed now on the latest commit.

**Comment by n3oney** [comment]
Thank you, it worked!
