### ISSUE TITLE
[Feature suggestion] Close window on click outside of main gtkbox

### ISSUE THREAD

**Issue by MininuxDev** [Kirottu/anyrun#20]
Hi, I think adding an option to close the runner when the user clicks outside of the main box could be nice.

Thanks for this awesome project by the way, it's super fast yet very extendable !

**Comment by Kirottu** [comment]
I'm glad you like it! And there is an option to close it when any kind of click is received outside the main box now.

**Comment by MininuxDev** [comment]
Awesome, thanks!
