### ISSUE TITLE
Support for max_entries/max_height

### ISSUE THREAD

**Issue by JustSimplyKyle** [Kirottu/anyrun#23]
options
`max_entries`/`max_height` could be added

**Comment by Kirottu** [comment]
I presume you mean max entries in total for all of the plugins?

**Comment by Kirottu** [comment]
Alright that should be done now, you can now limit the amount of entries with `max_entries: Some(<number of entries>)` in the config file.

**Comment by TheAyes** [comment]
@Kirottu Would you be so kind and add this as an example to your default config? I were trying
```
max_entries: 10
```
wondering why it wouldn't work. And in your usual docs there's nothing to be found about it. I only just found out, because I searched your entire repo for "max_entries".
