### ISSUE TITLE
Applications shows duplicate entries for files in ~/.local/share/applications

### ISSUE THREAD

**Issue by TheSunCat** [Kirottu/anyrun#26]
The applications plugin shows .desktop files that are in `/usr/local/share/applications` as well as ones which are in `$HOME/.local/share/applications`. Files in the local user folder are meant to be local overrides for applications, replacing the original entry. I use them to fix apps which require special environment variables to run on Wayland, and since switching to anyrun I have no way to differentiate between the original application entry which will not launch, and my local entry which does work.

**Comment by Kirottu** [comment]
I intended to do that but apparently messed it up. It should work now.

**Comment by TheSunCat** [comment]
Can confirm it works now. Thanks!
