### ISSUE TITLE
[Feature suggestion] Allow specifying source language in the translate plugin

### ISSUE THREAD

**Issue by n3oney** [Kirottu/anyrun#30]
Often times languages that are written in Cyrillic get mistaken for each other when the source language is automatic, and the results are mediocre.
Maybe there could be a format like `:ru-en <content>`?

**Comment by n3oney** [comment]
`:ru->en <content>` maybe as a workaround for chinese?

**Comment by Kirottu** [comment]
That would probably work for it yeah, so you could either do `:src->dest` or just `:dest` to translate stuff.

**Comment by n3oney** [comment]
Maybe even just source>dest, to make it 1 key less? Shouldn't hurt

**Comment by Kirottu** [comment]
Probably more reasonable yes.

**Comment by Kirottu** [comment]
Alright that should now be done. I also generally improved the translate plugin as it was having some issues.
