### ISSUE TITLE
Possibility to display results directly

### ISSUE THREAD

**Issue by Gajus84** [Kirottu/anyrun#31]
First of all, thank you for the good work. Anyrun is really fast and versatile. 

Would it be possible to add an option to display the input/results directly? Especially with the stdin plugin this would be handy. E.g. for the use with password scripts like Tessen. Here, several "selection menus" are run through and currently you always have to type the entries in the search to be able to select them.

**Comment by Kirottu** [comment]
This is something that I should do yeah, I will look into how I could make it work.

**Comment by Kirottu** [comment]
Alright on the latest commit this should now be possible with a config option.

**Comment by Gajus84** [comment]
Thank you, works perfectly. 

But only in the global config, right? Might be good to be able to choose there too. Now you can work with max_entries so this is no big deal for me, but it would be nice to have a choice.

**Comment by Kirottu** [comment]
I'm not sure if it can be implemented properly on a per plugin basis, but I am planning on adding a way to override any config option with args to the program. That could be used to only have this behavior when using said stdin plugin.

**Comment by Kirottu** [comment]
I'll close this issue now and will try to come up with a good way to override config options.
