### ISSUE TITLE
Can't find nautilus

### ISSUE THREAD

**Issue by JustSimplyKyle** [Kirottu/anyrun#34]
Not like this.
![image](https://github.com/Kirottu/anyrun/assets/68589851/57567dcc-80ac-4216-a092-8465e464d738)
Neither like this.
![image](https://github.com/Kirottu/anyrun/assets/68589851/db0dd590-b53b-4380-b733-d1f26e3aeea7)
and it doesn't seem to have more entries?
applications.ron:
```rust
Config(
  max_entries: 10, 
)
```

**Comment by Kirottu** [comment]
I ran into the same issue, it is a byproduct of desktop files in `~/.local/share/applications` overriding system level desktop entries. This means that the waydroid "Files" entry overrides the nautilus "Files" entry.

**Comment by JustSimplyKyle** [comment]
Hmm, wofi surprisngly can find it when searching files

**Comment by Kirottu** [comment]
It probably uses some other criteria as well with overrides. I guess more criteria like icon or something could be added to reduce occurrences like this.

**Comment by JustSimplyKyle** [comment]
Oh I haven't closed this
But I can in fact confirm that this works perfectly!
(maybe add a note in the Readme about similar issues like this)
