### ISSUE TITLE
On secondary monitors: Automatically selects all text instantly

### ISSUE THREAD

**Issue by NachtaktiverHalbaffe** [Kirottu/anyrun#36]
Hey,

first: Great work, I love this runner and its Plugins, it provides a krunner like experience outside of KDE. I use it in Hyprland, but I encounter an unexpected behaviour: When I launch the runner with only one monitor connected or on the second monitor, when it works as expected. But when I open it on some secondary monitors, then it automatically selects all text when typing, so effectively I only have one letter in the input unless i manually deselect the current entry after every letter i type (see attached video below.

As mentioned I use Hyprland as a Compositor and launch it with a keybind. On other runners like wofi it doesn't appear, so I think this behaviour is caused through a bug ln anyrun.

https://github.com/Kirottu/anyrun/assets/57433516/53deaaa1-2588-4e16-9f00-ffc3aa9508b7

My anyrun config (pretty much stock):

```ron
Config(
  // `width` and `vertical_offset` use an enum for the value it can be either:
  // Absolute(n): The absolute value in pixels
  // Fraction(n): A fraction of the width or height of the full screen (depends on exclusive zones and the settings related to them) window respectively
  
  // How wide the input box and results are.  
  width: Absolute(800), 
  
  // Where Anyrun is located on the screen: Top, Center
  position: Top, 

  // How much the runner is shifted vertically  
  vertical_offset: Fraction(0.3), 

  // Hide match and plugin info icons  
  hide_icons: false, 

  // ignore exclusive zones, f.e. Waybar  
  ignore_exclusive_zones: true, 

  // Layer shell layer: Background, Bottom, Top, Overlay  
  layer: Overlay, 
  
  // Hide the plugin info panel
  hide_plugin_info: false, 

  // Close window when a click outside the main box is received
  close_on_click: true,

  // Show search results immediately when Anyrun starts
  show_results_immediately: false,

  // Limit amount of entries shown in total
  max_entries: None,
  
  // List of plugins to be loaded by default, can be specified with a relative path to be loaded from the
  // `<anyrun config dir>/plugins` directory or with an absolute path to just load the file the path points to.
  plugins: [
    "libapplications.so",
    "libsymbols.so",
    "libshell.so",
    "libtranslate.so",
    "libkidex.so",
    "librink.so",
    //"libdictionary.so"
  ],
)
```

Hyprland keybind:
```
bind = CTRL $mainMod, P, exec, anyrun
```

**Comment by Kirottu** [comment]
I think I ran into this issue as well when using a secondary monitor I plugged in, but I just shrugged it off. I really don't know what would be causing this.

**Comment by NachtaktiverHalbaffe** [comment]
I launched it from the terminal and have gain some error logs, which doesnt appear when it works as expected:

```zsh
(anyrun:8152): Gtk-WARNING **: 14:20:45.002: Attempting to add a widget with type GtkListBox to a container of type GtkBox, but the widget is already inside a container of type GtkBox, please remove the widget from its existing container first.
```

Maybe this is helpful?

**Comment by Kirottu** [comment]
Hmm, I may have a hunch as to why it is happening. Can you test with the latest master branch if it is fixed now?

**Comment by NachtaktiverHalbaffe** [comment]
I've run with the AUR-git version (so it should be master) and it seems fixed. Thanks for fixing and im looking foward to the future of this project
