### ISSUE TITLE
Terminal applications do not appear

### ISSUE THREAD

**Issue by loqusion** [Kirottu/anyrun#43]
Terminal applications, such as ranger or btop++, are launched when you try to run them in the application menu, but no terminal appears; you can only see that they've been launched using a process viewer. The same applications work fine in rofi drun.

**Comment by Kirottu** [comment]
Hmm yeah that makes sense, I didn't think to handle those kinds of desktop entries. I do not know how to determine what the default terminal of the user is though.

**Comment by loqusion** [comment]
Rofi seems to do it based on finding the first terminal the user has installed on their system: https://github.com/davatorium/rofi/blob/b341ed01d2bdca60e2be5882f369c2f519101304/script/rofi-sensible-terminal

Perhaps we could do something like this as a default fallback, while allowing the user to configure their own preferred terminal in `config.ron` in case they have multiple terminal emulators installed on their system.

**Comment by Kirottu** [comment]
Yeah that seems like the best choice. I'll implement it soon enough.

**Comment by Kirottu** [comment]
The terminal setting must be set in the config file for the Applications plugin, look at the README of said plugin for info about configuring it.

**Comment by Kirottu** [comment]
Great, closing the issue now.
