### ISSUE TITLE
Allow moving anyrun to the left and right sides

### ISSUE THREAD

**Issue by Zettexe** [Kirottu/anyrun#53]
I would like to be able to have my anyrun dialog on the left side to fit with my current bar, please add this as a feature

It would likely be good to allow for the dialog to be placed anywhere on the screen as well

**Comment by Kirottu** [comment]
Hmm yeah I could create a placement mode where you just give the position, height and width and it is placed according to that to allow for any positioning like that.

**Comment by Kirottu** [comment]
Configuring it like this is now possible on the master branch.
