### ISSUE TITLE
Match box animation restarting

### ISSUE THREAD

**Issue by Zettexe** [Kirottu/anyrun#58]
The animation for the match box restarts every time you type a character into anyrun making a blinking effect. This doesnt seem to be intended.

**Comment by Kirottu** [comment]
Well, Anyrun recreates the match widgets on every keystroke so it is bound to happen. With the current internal design it isn't really possible to change this.

Besides, with some styles it is nice feedback for typing.

**Comment by Zettexe** [comment]
Would be nice if it could be changed as it messes with my eyes slightly. Is it possible to disable or change the animation?
