### ISSUE TITLE
Symbols plugin breaks with config files

### ISSUE THREAD

**Issue by Zettexe** [Kirottu/anyrun#60]
Using the default example config shown [here](https://github.com/Kirottu/anyrun/blob/master/plugins/symbols/README.md) does not work, anyrun runs without errors and the symbol does not show up.

**Comment by Zettexe** [comment]
Apparently the entire symbol selector stopped working after inserting the config, it still shows the symbols as usual but selecting any of them sets the clipboard to nothing.

**Comment by Kirottu** [comment]
If you run `anyrun` in the terminal what output does it give you?

**Comment by Zettexe** [comment]
Nothing

**Comment by Zettexe** [comment]
Actually if I omit the applications.ron file it complains that it cant find the file but it still breaks with just the applications.ron

**Comment by Kirottu** [comment]
That doesn't make sense, it works just fine with `applications.ron` and `symbols.ron` in my config dir.

**Comment by Zettexe** [comment]
Seems I was mistaken as for the cause of the symbols breaking, copying the symbols only breaks when im running anyrun through an intermediary script I use to handle animations in my bar. If I run anyrun through the terminal I do not have the issue. It does not seem like custom symbols get recognized in either case though.

**Comment by Kirottu** [comment]
It would seem like I forgot to update the readme to add the `prefix` field to the config, if you add that it should work fine.

**Comment by Zettexe** [comment]
I tried it with the new config and it still does not work.

**Comment by Kirottu** [comment]
It seems like the example config had a problem with the backslash trying to escape the underscore, it should work now though.

**Comment by Zettexe** [comment]
Yep, all working now thanks.
